- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove Old Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: Download and Extract Frontend Content
 # ansible.builtin.unarchive:
 #   src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
 #   dest: /usr/share/nginx/html
  #  remote_src: yes


## Download from Nexus
- name: Download and Extract {{ component }} Content
  ansible.builtin.unarchive:
    src: http://{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus_user', region='us-east-1') }}:{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus_pass', region='us-east-1') }}@nexus.tarak.cloud:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes


- name: Create Config in Nginx
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf    

- name: Create RoboShop Config in Nginx
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes



