{
 "title": "roboshop",
 "time": { "from": "2023-03-18T09:14:33.988Z", "to": "2023-03-18T09:19:53.116Z" },
 "panels": [
  {
   "title": "service status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{exported_name=\"cart.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"catalogue.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"nginx.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"user.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"shipping.service\", state=\"active\"}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"payment.service\", state=\"active\"}"
    }
   ]
  },
  {
   "title": "cpu %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (name) (rate (node_cpu_seconds_total{mode=\"idle\"}[1m])) *100)\r\n\r\n\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "server up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up\r\n", "legendFormat": "{{name}}" },
    {}
   ]
  },
  {
   "title": "memory %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100- (((node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * 100)"
    }
   ]
  }
 ]
}